---
services:
  jmeros-postgresql-db:
    image: postgres:18.4
    container_name: jmeros-postgresql-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-pass
      - POSTGRES_DB=reaction-observer-db
